### PR TITLE
Add execution parms

### PR DESCRIPTION
**Pull request by AnBenn**
Issue #65 
It's now possible to add execution parameters like:
check_interval: 
check_period: 
check_timeout: 
enable_active_checks: 
enable_event_handler: 
enable_notifications: 
enable_passive_checks: 
enable_perfdata: 
max_check_attempts: 
retry_interval:

on service apply level.

Attention: These parameters for service apply can't be edited via directory GUI!

### CODE REVIEW

**Comment by hektor1966** [comment]
good job!

**Comment by rndmh3ro** [comment]
Hi @AnBenn,

thanks for this. There are two things you still need to do:

* add the new parameters to the examples: https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/a7b3922e162a2570c52c36249682e9b9974111b1/plugins/modules/icinga_service_apply.py#L205
You can also add a new example if you want to.

* After extending the examples, you need to run the `update_examples_and_tests.sh` script inside the `hacking` folder. This updates all examples and tests to ensure functionality. You'll need to have yq (https://mikefarah.gitbook.io/yq/) installed for this to work.

**Comment by AnBenn** [comment]
Hi @rndmh3ro,

The existing example in icinga_service_apply.py is already nice and self-explaining. Adding more Parameters to the example won't improve the value. 

However, if you like the idea of having a more complex example or it is important for testing purposes, then let me know and I'll do it.

**Comment by rndmh3ro** [comment]
> However, if you like the idea of having a more complex example or it is important for testing purposes, then let me know and I'll do it.

It is indeed important for testing, as otherwise the new options won't be tested at all. Please add them. :)

**Comment by AnBenn** [comment]
Makes sense, I'll do it.

**Pull request merged**
