### PR TITLE
Add command_endpoint parameter to host and host_template

### PR DESCRIPTION
**Pull request by jensrudolf**
Hi,

this PR adds the 'command_endpoint' parameter to the host and host_template modules. I also added them to examples and tests. I would appriciate having this change upstream as we use it to deploy our host checks to the respective Icinga2 satellites.

BR
Jens Rudolf

### CODE REVIEW

**Comment by rndmh3ro** [comment]
Thanks!

Two things:
* the command_endpoint needs to exist, not sure what's best to insert here. `localhost` or `host.vars.agent_endpoint`?
* The tests and examples are updated from a bash-script, see here: https://github.com/T-Systems-MMS/ansible-collection-icinga-director#updating-the-tests-and-examples

**Comment by jensrudolf** [comment]
Hi @rndmh3ro,

thanks for the info. Shall I remove the tests and examples from the commit and regenerate them via the provided bash script? Regarding the command_endpoint, I would change it to "host.vars.agent_endpoint" to make it more clear that is different from the master.

**Comment by rndmh3ro** [comment]
> Shall I remove the tests and examples from the commit and regenerate them via the provided bash script?

No need to remove them, the script will overwrite the existing tests. The commits will then get squashed.

**Comment by jensrudolf** [comment]
The integration tests are still unhappy probably because of the endpoint being non-existent. Not sure either, whether the variable "host.vars.agent_endpoint" is correctly dereferenced. I am unsure how to fix this.

**Comment by rndmh3ro** [comment]
I just checked in the frontend and there, there is only a menu to choose from items, no way to enter custom variables.
We do however have a endpoint defined in our tests - `fooendpoint` - can you please try this one?

**Comment by jensrudolf** [comment]
I changed the endpoint to "fooendpoint" as suggested. Seems like integration tests are happy with it now.

**Comment by rndmh3ro** [comment]
Thank you!

**Pull request merged**
